### ISSUE TITLE
Problem installing QsRutils

### ISSUE THREAD

**Issue by pauGuas** [jfq3/QsRutils#1]
Hi, I need to use the veganotu function but haven't been able to install the QsRutils packages.  Has anyone else had problems?

Code I have tried:
devtools::install_github("jfq3/RDPutils", dependencies = TRUE)

install.packages("remotes")
remotes::install_github("jfq3/QsRutils")

**Comment by jfq3** [comment]
If you closed the issue, I assume you solved your problem?

**Comment by pauGuas** [comment]
@jfq3  yes, sorry, I figured it out.  Thank you!  But perhaps you could help me with a bioenv error I'm getting?

**Comment by jfq3** [comment]
Email me directly at quensenj@msu.edu and I will see what I can do to help you out.
